source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'paperclip'
gem 'sorcery'
gem 'pry-rails'
gem 'bootstrap-sass', '~> 3.3.5'

group :doc do
  gem 'sdoc', require: false
end
